# Generated by Django 5.0.6 on 2024-05-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('edad', models.IntegerField()),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padres.padres')),
            ],
        ),
    ]
